== Allgemeines
=== Ziel und Zweck
Dieses Dokument beschreibt den Geobasisdatensatz
 
* *__Waldreservate__.*

Waldreservate sind wichtige Instrumente zur Förderung der ökologischen und biologischen Vielfalt im Wald. Bund und Kantone haben sich verpflichtet, bis ins Jahr 2030 10 % der Waldfläche als Waldreservate auszuscheiden.

Im Kanton Schwyz stehen aktuell insgesamt gut 13 % der Waldfläche als Waldreservate unter Vertrag. Total sind es 3'646 ha, wovon 1'729 ha als Naturwald- und 1'917 ha als Sonderwaldreservate. Grundlage dazu bildet das bereits im Jahr 1999 erarbeitete Waldreservatskonzept. Dieses wurde in der Folge konsequent und erfolgreich umgesetzt, so dass bis 2007 bereits gut 8 % der kantonalen Waldfläche als Waldreservate gesichert werden konnten, und 2018 der heutige Anteil von 13 % erreicht war.

Der Geobasisdatensatz ist Bestandteil des ÖREB-Katasters.

=== rechtliche Grundlagen
Seit dem 1. Juli 2008 ist das Bundesgesetz über Geoinformation (GeoIG, SR 510.62) <<allgemeines.adoc#doc-01,[1]>> in Kraft. Am 1. Juli 2012 erfolgte die vollständige Inkraftsetzung des kantonalen Geoinformationsgesetzes (kGeoiG, SRSZ 214.110) <<allgemeines.adoc#doc-03,[3]>>. Es hat zum Ziel, verbindliche Vorgaben für die Erfassung, Modellierung und den Austausch von Geodaten festzulegen. +

Am 1. Januar 2013 trat die kantonale Verordnung über Geoinformation (kGeoiV, SRSZ 214.111) <<allgemeines.adoc#doc-04,[4]>> in Kraft. Sie präzisiert das kGeoiG in fachlicher sowie technischer Hinsicht und führt im Anhang 1 den „Katalog der Geobasisdaten des Bundesrechts mit Zuständigkeit beim Kanton“ und im Anhang 2 den „Katalog der Geobasisdaten des kantonalen Rechts“. Darin werden die Fachstellen definiert, welche für die Ausarbeitung eines Geodatenmodells zuständig sind.

=== Zielgruppen
Dieses Dokument richtet sich an folgende Nutzergruppen:

* **Fachstellen für Modellierung,** die den inhaltlichen Rahmen des Themas festlegen,
* **Datenbearbeiterinnen und -bearbeiter,** die sich über die Prozesse und Methoden der Datenpflege informieren,
* **Verantwortliche für die Datenpublikation,** die die Daten entsprechend der Freigabestufe veröffentlichen und die Transformation in andere Modelle durchführen sowie
* **Endnutzerinnen und Endnutzer,** die sich über den Inhalt und die Struktur der Daten informieren möchten.

ifdef::backend-pdf[]
<<<
endif::[]
