== Modellbeschreibung

Im Strategie-Dokument «Waldpolitik 2020» <<allgemeines.adoc#doc-06,[06]>> hat der Bund das Ziel festgelegt, dass bis 2030 mindestens 10 % der Schweizer Waldfläche als Waldreservate gesichert sein müssen. Die Umsetzung dieser Vorgabe ist Sache der Kantone und erfolgt anhand von Programmvereinbarungen zwischen dem Bund und den Kantonen.

Im Kanton Schwyz sind 6.4 % der Waldfläche als Naturwaldreservate und 7.1 % als Sonderwaldreservate eingerichtet und vertraglich auf 50 Jahre gesichert. Die 34 Naturwaldreservate umfassen insgesamt 1’729 ha, die 9 Sonderwaldreservate 1’917 ha (Stand 2024). Grundlage dazu bildet das bereits im Jahr 1999 erarbeitete Waldreservatskonzept <<allgemeines.adoc#doc-07,[07]>>. Dieses wurde in der Folge konsequent und erfolgreich umgesetzt, so dass bis 2007 bereits gut 8 % der kantonalen Waldfläche als Waldreservate gesichert werden konnten und 2018 der heutige Anteil von 13 % erreicht war. Das Waldreservatskonzept unterschiedet zwischen:

*	**Naturwaldreservaten** (MCPFE-Class 1.2), wo gänzlich auf forstliche Eingriffe verzichtet wird und der Wald sich natürlich entwickeln kann, und
*	**Sonderwaldreservaten** (MCPFE-Class 1.3), in welchen gezielt eingegriffen wird, um bedrohte Arten zu fördern.

Für die Publikation im ÖREB-Kataster ist für jede Geometrie ihre Rechtsvorschrift zuzuordnen. Bei Waldreservaten ist die Rechtsvorschrift der Vertrag, welcher die zuständige Stelle mit dem Eigentümer abschliesst. Der Vertrag kann Personen- wie Finanzdaten enthalten, welche nicht für eine Veröffentlichung vorgesehen waren. Der Bund hat dies erkannt und darauf reagiert. Er schreibt in Kapitel 3.16.2 in <<allgemeines.adoc#doc-05,[05]>>, dass die Rechtsvorschrift bei Waldreservaten wie folgt gestaltet werden kann: +
__"Die Verträge mit Waldbewirtschaftern selber müssen nicht zwingend als Rechtsvorschrift verlinkt werden. In dem Falle ist bei den Rechtsvorschriften der Name des Vertrages anzugeben, damit sich Interessierte bei der zuständigen Fachstelle erkundigen können."__

Die zuständige kantonale Stelle entschied, folgende Attribute zu führen:

* Vertragsname
* Vertragspartner
* Kontaktadresse

ifdef::backend-pdf[]
<<<
endif::[]
